### ISSUE TITLE
builds for python 3.9 didn't upload... could be noarch

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/entrypoints-feedstock#17]
- blocks https://github.com/conda-forge/nbconvert-feedstock/pull/48

Looks like the merge of #16 didn't result in [uploads](https://anaconda.org/conda-forge/entrypoints/files). Might just need an empty commit.

However, the only selector is for `py27`, so this could probably be `noarch: python` now :tada:

**Comment by ocefpaf** [comment]
They are in now. It should take ~40 min until the CDN syncs and we can restart nbconvert. Thanks!
